services:

  mysql:
    image: mysql:8.0
    container_name: ebank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebank_db
      MYSQL_USER: ebank
      MYSQL_PASSWORD: ebank123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ebank-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8089:80"
    depends_on:
      mysql:
        condition: service_healthy

  app:
    image: layegaye/ebank:1.0.0  # ← utilise l'image Docker Hub au lieu de build
    container_name: ebank-app
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ebank_db
      SPRING_DATASOURCE_USERNAME: ebank
      SPRING_DATASOURCE_PASSWORD: ebank123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: