spring:
  application:
    name: ebank

  datasource:
    url: jdbc:mysql://localhost:3306/ebank_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

keycloak:
  auth-server-url: http://localhost:8180
  realm: ebank-realm
  client-id: ebank-client
  client-secret: UTltiZwYTYRgy7PPkPaSD79RoSb2OPQf

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true

app:
  jwt:
    secret: ${JWT_SECRET:YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc=}
    expiration: ${JWT_EXPIRATION:1800000}  # 30 minutes par défaut (1000*60*30)

logging:
  level:
    sn.xoslu.tech.ebank.feign: DEBUG  # ← remplace par ton package
    feign: DEBUG

feign:
  client:
    config:
      keycloak-client:
        loggerLevel: FULL