# ─────────────────────────────────────────
# Keycloak Service — Identity Provider
# ─────────────────────────────────────────
services:
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: ebank-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8180:8080"
    networks:
      - ebank-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  ebank-network:
    external: true